Gallery/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artwork.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [

	# User Auths
	path("sign-up/", views.register_view, name="sign-up"),
	path("sign-in/", views.login_view, name="sign-in"),
	path("sign-out/", views.logout_view, name="sign-out"),

	# User Account
	path("account/", views.account, name="account"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.html import mark_safe

class User(AbstractUser):
	email = models.EmailField(unique=True)
	username = models.CharField(max_length=100)
	name = models.CharField(max_length=100, null=True, blank=True, default='')
	phone = models.CharField(max_length=100, null=True, blank=True, default='')
	bio = models.CharField(max_length=100, null=True, blank=True, default='')
	image = models.ImageField(upload_to='account-images', default="user.jpg")

	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ['username']

	def user_image(self):
		return mark_safe('<img src="%s" width="50" height="50">' % (self.image.url))

	def __str__(self):
		return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
from django.core.exceptions import ValidationError

class UserRegisterForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'username-validation'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

	class Meta:
		model = User
		fields = ['username', 'email']

	def clean_username(self):
		username = self.cleaned_data['username']

		if ' ' in username:
			raise ValidationError("Username cannot contain spaces.")

		if len(username) < 3 or len(username) > 12:
			raise ValidationError("Username must be between 3 and 12 characters.")
			
		return username

userauths/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from userauths.models import User
from userauths.forms import UserRegisterForm

# User = settings.AUTH_USER_MODEL

def register_view(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST or None)

		if form.is_valid():
			new_user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"Hey {username}, Your account was created successfully")
			new_user = authenticate(username=form.cleaned_data['email'], 
									password=form.cleaned_data['password1'] 	
				)
			login(request, new_user)

			return redirect("artwork:artwork")
	else:
		form = UserRegisterForm()

	context = {
		'form': form
	}

	return render(request, 'userauths/sign-up.html', context)

def login_view(request):
    if request.user.is_authenticated:
        return redirect('artwork:artwork')

    next_url = request.GET.get('next', None)

    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")

                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('artwork:artwork')
            else:
                messages.warning(request, "Password is wrong.")
        except User.DoesNotExist:
            messages.warning(request, f"User with {email} does not exist!")

    return render(request, 'userauths/sign-in.html')

def logout_view(request):
	logout(request)
	messages.success(request, "You logged out.")
	return redirect('userauths:sign-in')

@login_required
def account(request):
	if request.method == 'POST':
		
		new_username = request.POST.get('username').replace(" ", "").lower()

		if ' ' in new_username:
			messages.warning(request, "Username cannot contain spaces.")
			return redirect('userauths:account')

		if len(new_username) < 3 or len(new_username) > 12:
			messages.warning(request, 'Username must be between 3 and 12 characters.')
			return redirect('userauths:account')

		if User.objects.filter(username=new_username).exclude(id=request.user.id).exists():
			messages.warning(request, f'Username "{new_username}" is already taken!')
			return redirect('userauths:account')

		request.user.username = new_username
		request.user.save()

		new_name = request.POST.get('name')
		new_phone = request.POST.get('phone')
		new_bio = request.POST.get('bio')
		new_image = request.FILES.get('image')

		account = request.user
		account.name = new_name
		account.phone = new_phone
		account.bio = new_bio

		if new_image:
			account.image = new_image
			
		account.save()

		messages.success(request, 'Account updated successfully.')

		return redirect('userauths:account')	

	return render(request, 'userauths/account.html')

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Sign In{% endblock title %}

{% block content %}

<div class="auth_wrapper">
    <header class="auth_header">Sign in</header>
    <form method="POST" class="auth_form">
      {% csrf_token %}
      <div class="field email">
        <div class="input-area">
          <input type="text" required name="email" placeholder="Email Address">
          <i class="icon fas fa-envelope"></i>
          {% if messages %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if messages %}
          {% for message in messages %}
            <div class="error error-txt">
              <strong>{{ message }}</strong>
            </div>
          {% endfor %}
        {% endif %}
      </div>
      <div class="field password">
        <div class="input-area">
          <input type="password" required name="password" placeholder="Password">
          <i class="icon fas fa-lock"></i>
          <!-- <i class="error error-icon fas fa-exclamation-circle"></i> -->
        </div>
        <!-- <div class="error error-txt">Password can't be blank</div> -->
      </div>
      <div class="pass-txt"><a href="#">Forgot password?</a></div>
      <input type="submit" value="Sign in">
    </form>
  <div class="sign-txt">Not yet member? <a href="{% url 'userauths:sign-up' %}">Sign up now</a></div>
</div>

{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Sign Up{% endblock title %}

{% block content %}

<div class="auth_wrapper">
    <header class="auth_header">Sign up</header>
    <form method="POST" class="auth_form">
      {% csrf_token %}
      <div class="field">
        <div class="input-area">
          {{ form.email }}
          <i class="icon fas fa-envelope"></i>
          {% if form.email.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.email.errors %}
        <div class="error error-txt">
          <strong>{{ form.email.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <div class="field">
        <div class="input-area">
          {{ form.username }}
          <i class="icon fas fa-user"></i>
          {% if form.username.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.username.errors %}
        <div class="error error-txt">
          <strong>{{ form.username.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <div class="field">
        <div class="input-area">
          {{ form.password1 }}
          <i class="icon fas fa-lock"></i>
          {% if form.password1.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.password1.errors %}
        <div class="error error-txt">
          <strong>{{ form.password1.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <div class="field">
        <div class="input-area">
          {{ form.password2 }}
          <i class="icon fas fa-lock"></i>
          {% if form.password2.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.password2.errors %}
        <div class="error error-txt">
          <strong>{{ form.password2.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <input type="submit" value="Sign up">
    </form>
  <div class="sign-txt">Already have an account? <a href="{% url 'userauths:sign-in' %}">Sign in now</a></div>
</div>

{% endblock content %}